### ISSUE TITLE
title or journalTitle

### ISSUE THREAD

**Issue by JochenVanSeveren** [MrClassicT/bibla#3]
```bib
@article{Nissi2021,
  title={Improving Event Management Implementation on Odoo Business Management Software},
  author={Nissi, Miika},
  date={2021}
}
```
I got this:
`bachproef/bachproef.bib:10 M01ArticleJournaltitle: Missing required field journaltitle for entry type article`

Changed title to journaltitle
```bib
@article{Nissi2021,
  journaltitle={Improving Event Management Implementation on Odoo Business Management Software},
  author={Nissi, Miika},
  date={2021}
}
```
And got this: `bachproef/bachproef.bib:10 M01ArticleTitle: Missing required field title for entry type article`

Which one is it : )

**Comment by MrClassicT** [comment]
Was this by using `bibla lint {file.bib}`? Or did a custom command get used?

**Comment by JochenVanSeveren** [comment]
> Was this by using `bibla lint {file.bib}`? Or did a custom command get used?

The default command was used

**Comment by bertvv** [comment]
This is not a bug. The field `title` is for the title of the article. However, if you cite an article, you have to specify in what journal it appeared. That's what the `journaltitle` field is for.

Hence, the feedback from the tool is correct, the bibliographical data is incomplete. Only author, title and date are not sufficient to find the cited source.

**Comment by JochenVanSeveren** [comment]
> This is not a bug. The field `title` is for the title of the article. However, if you cite an article, you have to specify in what journal it appeared. That's what the `journaltitle` field is for.
> 
> Hence, the feedback from the tool is correct, the bibliographical data is incomplete. Only author, title and date are not sufficient to find the cited source.

Oh that clarifies it 
Thank you!
